### ISSUE TITLE
bug: always auto repeat button not work if screen ia off.

### ISSUE THREAD

**Issue by danieloox** [inotia00/revanced-patches#26]
### Type

Other

### Bug description

if always auto repeat is on - not work if screen is off. next video is played. if screen is on working normally.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

.

### Solution

.

### Additional context

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Spacellary** [comment]
YouTube 17.40.41 (recommended)
Patches version 2.85.1

Auto-play: OFF
Auto-repat: ON

Video is repeating without issues here for me.
You could try a different account or check if you have the latest patches version.

**Comment by danieloox** [comment]
I mean always auto repeat options. it should also work when the screen is off. and it is not. i use the button on the player for this. you can set this up in the extended settings.

**Comment by danieloox** [comment]
clean install, all newest, and try with other accounts, and try with only always auto repeat in settings without player button. still not work on screen off. if screen is on is working good.

**Comment by danieloox** [comment]
I tried on OG revanced and it works fine with the screen is off.

**Comment by Spacellary** [comment]
I don't have the `always  auto repeat`, I just use the this button down there in the player. You could use that instead, I believe the only reason "always auto repeat" patch was a thing the way it was is because they couldn't do it like that in Revanced, as I think it's a much better way, just enable it and it should be fine.

#### 🔁
![Screenshot_2022-10-22-15-11-23-660_app rvx android youtube](https://user-images.githubusercontent.com/39604793/197356415-038c2527-182f-4380-bd90-158e245e0a02.jpg)

**Comment by danieloox** [comment]
THIS OPTION NOT WORK IF SCREEN IS OFF. NEXT VIDEO IS PLAYED.

**Comment by Spacellary** [comment]
Well until inotia00 is able to look into it, maybe you can try buying again **without** `always auto repeat` patch, and see if works that way. I don't have it here and it works fine. Maybe that helps you.
I don't have that patch installed and the auto repeat button (🔁) is working.

**Comment by danieloox** [comment]
@Spacellary move the video towards the end, turn off the screen and see if the same video repeats on the off screen. btw you use latest inotia patches?

**Comment by Spacellary** [comment]
@danieloox Yes, I'm using latest 2.85.1 patches, I just tested on different videos, it works here.

**Comment by danieloox** [comment]
ok fine. I'm not looking for help. I'm just reporting a bug.

**Comment by Spacellary** [comment]
Yeah I know, just seeing if I can help but if it's a bug it has to be looked into.
I didn't add the `always auto repeat` patch though. It's not needed. So maybe why it's not happening here. Keeping an eye on it just in case.

**Comment by danieloox** [comment]
@Spacellary 
since you did not select this option, and use it and it works for you. yes, this is a bug 😂

**Comment by danieloox** [comment]
oh i exclude always auto repeat but this option still not working on off screen for me.

**Comment by danieloox** [comment]
@Spacellary what version of yt are you using

**Comment by Spacellary** [comment]
17.40.41

**Comment by danieloox** [comment]
oh i too. its weird. on og revanced this option working good.

**Comment by danieloox** [comment]
@inotia00

**Comment by danieloox** [comment]
after excluding this patch, it stopped working on the enabled screen too.

**Comment by inotia00** [comment]
write a list of patches you included and excluded.

**Comment by danieloox** [comment]
@inotia00 all without microg, material you, icon blue, icon red, alternative icons. custom branding name, custom package name. i use normal overlay buttons and revancify icon. im root and use rvx builder.

**Comment by inotia00** [comment]
I found the cause of the issue.
It will be fixed in the next release

**Comment by danieloox** [comment]
Awesome. especially useful when listening to music in the car :)

**Comment by inotia00** [comment]
Fixed in v2.85.2

**Comment by danieloox** [comment]
@inotia00 always auto repeat still don't work if screen is off on 2.85.2 for me :(

**Comment by danieloox** [comment]
@inotia00 ok i tried only these patches:
![Screenshot_20221024-123908_Brave](https://user-images.githubusercontent.com/113600273/197508978-7f7ce92c-75f7-4f14-a9aa-79be932065a6.jpg)
and always auto repeat works good on off screen. hmm.

**Comment by inotia00** [comment]
Can you show the patches excluded or included?
The environment I tested was when everything was checked by default.

**Comment by danieloox** [comment]
@inotia00 I think I found a bug. I have now removed the cache and storage yt and the problem persists. i always did it after installation extended maybe there was a bug here. ok i will try all patches again but i won't wipe any data.

**Comment by danieloox** [comment]
> @inotia00 I think I found a bug. I have now removed the cache and storage yt and the problem persists. i always did it after installation extended maybe there was a bug here. ok i will try all patches again but i won't wipe any data.

@inotia00  oh no this is not a bug. still after all patches. i now not clear any data :(

**Comment by danieloox** [comment]
@inotia00 i go try with revancify tool.

**Comment by danieloox** [comment]
@inotia00 oh same with revancify. it looks like with the screen off, the movie plays again for a fraction of a second and then immediately skips to another movie.

**Comment by danieloox** [comment]
i use all your default selected patches exclude only microg and still same.

**Comment by danieloox** [comment]
I tried the option in the settings without a button but still the same. with the screen on, each method works.

**Comment by danieloox** [comment]
I'll try to install a non-root version with microg.

**Comment by danieloox** [comment]
> I'll try to install a non-root version with microg.

same problem :(

**Comment by danieloox** [comment]
since it works for og revanced, it doesn't seem to be a problem on my side.

**Comment by inotia00** [comment]
Check all patches and proceed, and test again

**Comment by danieloox** [comment]
yea same versions on me. weird.

**Comment by danieloox** [comment]
@inotia00 i turn on the "turn off new layout (experimental)" option and picture in picture and it looks like it's all good now.

**Comment by inotia00** [comment]
If so... maybe it's another A/B test from Google
(Because that option is an option to forcibly disable A/B testing)

I will close this issue for now

**Comment by danieloox** [comment]
if I add a second video to my playlist, the first one will end and the second one will play with the screen off, even with always auto repeat.

**Comment by danieloox** [comment]
Anyway, now nothing turns on automatically and always auto repeat works, so thanks. only in the playlist I have to listen on the screen on when I want it to repeat.

**Comment by danieloox** [comment]
@inotia00 ok it looks like it doesn't work when autoplay is on. Maybe make the autoplay option turn off when you turn on always auto repeat, and when you turn on the autoplay option, turn off always auto repeat. I don't know if it is possible, but it would be a nice solution for sure.

**Comment by danieloox** [comment]
if always auto repeat is on, auto repeat is not needed anyway, and if you want to turn it on, always auto repeat will turn off. or one could make such that instead of the always auto repeat option and a button for that in the player, there is simply an autoplay option which automatically turns on always auto repeat when turned off. or off when turned on.

**Comment by danieloox** [comment]
@inotia00 or make a triple switch. there will be nothing on one option (video stops), on the second option there will be autoplay (next video is play) and on the third option always auto repeat. I think that would be a great solution.

**Comment by danieloox** [comment]
@inotia00 It would have to look like that in the first position all options would be turned off, on the second the autoplay option would turn on and on the third the always auto repeat option would turn on and the autoplay option would then have to turn off, and again when returning to the first option the option always auto repeat would be turned off so all options would be turned off :)

**Comment by danieloox** [comment]
triple switch.
0 tap -all options off.
1 tap- autoplay on.
2 tap- autoplay off and always autorepeat on.
3 tap- always autorepeat off (back to 0)
and again.

**Comment by inotia00** [comment]
The github issues page is not your diary. Stop spam.

Create a new issue page with a brief summary of the circumstances under which the bug occurs, with screenshots.
